import postgres from 'postgres';
import {
	SECRET_POSTGRES_URL,
	SECRET_POSTGRES_PRISMA_URL,
	SECRET_POSTGRES_URL_NON_POOLING,
	SECRET_POSTGRES_USER,
	SECRET_POSTGRES_HOST,
	SECRET_POSTGRES_PASSWORD,
	SECRET_POSTGRES_DATABASE
} from '$env/static/private';

const sql = postgres(SECRET_POSTGRES_URL);
