export const Skills = [
	{ id: 0, name: '1H Blunt', isTrade: false },
	{ id: 1, name: '1H Slashing', isTrade: false },
	{ id: 2, name: '2H Blunt', isTrade: false },
	{ id: 3, name: '2H Slashing', isTrade: false },
	{ id: 4, name: 'Abjuration', isTrade: false },
	{ id: 5, name: 'Alteration', isTrade: false },
	{ id: 6, name: 'Apply Poison', isTrade: false },
	{ id: 7, name: 'Archery', isTrade: false },
	{ id: 8, name: 'Backstab', isTrade: false },
	{ id: 9, name: 'Bind Wound', isTrade: false },
	{ id: 10, name: 'Bash', isTrade: false },
	{ id: 11, name: 'Block', isTrade: false },
	{ id: 12, name: 'Brass Instruments', isTrade: false },
	{ id: 13, name: 'Channeling', isTrade: false },
	{ id: 14, name: 'Conjuration', isTrade: false },
	{ id: 15, name: 'Defense', isTrade: false },
	{ id: 16, name: 'Disarm', isTrade: false },
	{ id: 17, name: 'Disarm Traps', isTrade: false },
	{ id: 18, name: 'Divination', isTrade: false },
	{ id: 19, name: 'Dodge', isTrade: false },
	{ id: 20, name: 'Double Attack', isTrade: false },
	{ id: 21, name: 'Dragon Punch', isTrade: false },
	{ id: 22, name: 'Dual Wield', isTrade: false },
	{ id: 23, name: 'Eagle Strike', isTrade: false },
	{ id: 24, name: 'Evocation', isTrade: false },
	{ id: 25, name: 'Feign Death', isTrade: false },
	{ id: 26, name: 'Flying Kick', isTrade: false },
	{ id: 27, name: 'Forage', isTrade: false },
	{ id: 28, name: 'Hand to Hand', isTrade: false },
	{ id: 29, name: 'Hide', isTrade: false },
	{ id: 30, name: 'Kick', isTrade: false },
	{ id: 31, name: 'Meditate', isTrade: false },
	{ id: 32, name: 'Mend', isTrade: false },
	{ id: 33, name: 'Offense', isTrade: false },
	{ id: 34, name: 'Parry', isTrade: false },
	{ id: 35, name: 'Pick Lock', isTrade: false },
	{ id: 36, name: '1H Piercing', isTrade: false },
	{ id: 37, name: 'Riposte', isTrade: false },
	{ id: 38, name: 'Round Kick', isTrade: false },
	{ id: 39, name: 'Safe Fall', isTrade: false },
	{ id: 40, name: 'Sense Heading', isTrade: false },
	{ id: 41, name: 'Singing', isTrade: false },
	{ id: 42, name: 'Sneak', isTrade: false },
	{ id: 43, name: 'Specialize Abjure', isTrade: false },
	{ id: 44, name: 'Specialize Alteration', isTrade: false },
	{ id: 45, name: 'Specialize Conjuration', isTrade: false },
	{ id: 46, name: 'Specialize Divination', isTrade: false },
	{ id: 47, name: 'Specialize Evocation', isTrade: false },
	{ id: 48, name: 'Pick Pockets', isTrade: false },
	{ id: 49, name: 'Stringed Instruments', isTrade: false },
	{ id: 50, name: 'Swimming', isTrade: false },
	{ id: 51, name: 'Throwing', isTrade: false },
	{ id: 52, name: 'Tiger Claw', isTrade: false },
	{ id: 53, name: 'Tracking', isTrade: false },
	{ id: 54, name: 'Wind Instruments', isTrade: false },
	{ id: 55, name: 'Fishing', isTrade: true },
	{ id: 56, name: 'Make Poison', isTrade: true },
	{ id: 57, name: 'Tinkering', isTrade: true },
	{ id: 58, name: 'Research', isTrade: true },
	{ id: 59, name: 'Alchemy', isTrade: true },
	{ id: 60, name: 'Baking', isTrade: true },
	{ id: 61, name: 'Tailoring', isTrade: true },
	{ id: 62, name: 'Sense Traps', isTrade: false },
	{ id: 63, name: 'Blacksmithing', isTrade: true },
	{ id: 64, name: 'Fletching', isTrade: true },
	{ id: 65, name: 'Brewing', isTrade: true },
	{ id: 66, name: 'Alcohol Tolerance', isTrade: false },
	{ id: 67, name: 'Begging', isTrade: false },
	{ id: 68, name: 'Jewelry Making', isTrade: true },
	{ id: 69, name: 'Pottery', isTrade: true },
	{ id: 70, name: 'Percussion Instruments', isTrade: false },
	{ id: 71, name: 'Intimidation', isTrade: false },
	{ id: 72, name: 'Berserking', isTrade: false },
	{ id: 73, name: 'Taunt', isTrade: false },
	{ id: 74, name: 'Frenzy', isTrade: false },
	{ id: 75, name: 'Remove Trap', isTrade: true },
	{ id: 76, name: 'Triple Attack', isTrade: false },
	{ id: 77, name: '2H Piercing, isTrade:false' }
];

export const getAllTradeSkills = () => {
	return Skills.filter((value) => {
		return value.isTrade;
	}).sort((a, b) => a.name.localeCompare(b.name));
};

export const getSkillById = (id: number) => {
	let value = Skills.find((value) => {
		return value.id === id;
	});
	if (value === undefined) return { id: -1, name: 'undefined', isTrade: false };
	return value;
};
