import {z} from 'zod';
export const CharacterCorpsesBackupSchema= z.object({
beard: z.number(),
beard_color: z.number(),
charid: z.number(),
charname: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
class: z.number(),
copper: z.number(),
deity: z.number(),
exp: z.number(),
eye_color_1: z.number(),
eye_color_2: z.number(),
face: z.number(),
gender: z.number(),
gmexp: z.number(),
gold: z.number(),
hair_color: z.number(),
hair_style: z.number(),
heading: z.number(),
helm_texture: z.number(),
id: z.number(),
is_buried: z.number(),
is_locked: z.number(),
is_rezzed: z.number(),
killedby: z.number(),
level: z.number(),
platinum: z.number(),
race: z.number(),
rez_time: z.number(),
rezzable: z.number(),
silver: z.number(),
size: z.number(),
texture: z.number(),
time_of_death: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
was_at_graveyard: z.number(),
wc_1: z.number(),
wc_2: z.number(),
wc_3: z.number(),
wc_4: z.number(),
wc_5: z.number(),
wc_6: z.number(),
wc_7: z.number(),
wc_8: z.number(),
wc_9: z.number(),
x: z.number(),
y: z.number(),
z: z.number(),
zone_id: z.number(),
});
export type CharacterCorpsesBackupType = z.infer<typeof CharacterCorpsesBackupSchema>;
