import {z} from 'zod';
export const NpcTypesSchema= z.object({
AC: z.coerce.number(),
AGI: z.coerce.number(),
ATK: z.coerce.number(),
Accuracy: z.coerce.number(),
CHA: z.coerce.number(),
CR: z.coerce.number(),
DEX: z.coerce.number(),
DR: z.coerce.number(),
FR: z.coerce.number(),
MR: z.coerce.number(),
PR: z.coerce.number(),
STA: z.coerce.number(),
STR: z.coerce.number(),
WIS: z.coerce.number(),
_INT: z.coerce.number(),
aggro_pc: z.coerce.number(),
aggroradius: z.coerce.number(),
armortint_blue: z.coerce.number(),
armortint_green: z.coerce.number(),
armortint_id: z.coerce.number(),
armortint_red: z.coerce.number(),
armtexture: z.coerce.number(),
assistradius: z.coerce.number(),
attack_count: z.coerce.number(),
attack_delay: z.coerce.number(),
avoidance: z.coerce.number(),
bodytype: z.coerce.number(),
bracertexture: z.coerce.number(),
chesttexture: z.coerce.number(),
class: z.coerce.number(),
combat_hp_regen: z.coerce.number(),
combat_mana_regen: z.coerce.number(),
d_melee_texture1: z.coerce.number(),
d_melee_texture2: z.coerce.number(),
emoteid: z.coerce.number(),
encounter: z.coerce.number(),
engage_notice: z.coerce.number(),
exp_pct: z.coerce.number(),
face: z.coerce.number(),
feettexture: z.coerce.number(),
flymode: z.coerce.number(),
gender: z.coerce.number(),
greed: z.coerce.number(),
handtexture: z.coerce.number(),
healscale: z.coerce.number(),
helmtexture: z.coerce.number(),
hp: z.coerce.number(),
hp_regen_rate: z.coerce.number(),
id: z.coerce.number(),
ignore_despawn: z.coerce.number(),
ignore_distance: z.coerce.number(),
isquest: z.coerce.number(),
lastname: z.coerce.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
legtexture: z.coerce.number(),
level: z.coerce.number(),
light: z.coerce.number(),
loottable_id: z.coerce.number(),
luclin_beard: z.coerce.number(),
luclin_beardcolor: z.coerce.number(),
luclin_eyecolor: z.coerce.number(),
luclin_eyecolor2: z.coerce.number(),
luclin_haircolor: z.coerce.number(),
luclin_hairstyle: z.coerce.number(),
mana: z.coerce.number(),
mana_regen_rate: z.coerce.number(),
maxdmg: z.coerce.number(),
maxlevel: z.coerce.number(),
merchant_id: z.coerce.number(),
mindmg: z.coerce.number(),
name: z.coerce.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
npc_aggro: z.coerce.number(),
npc_faction_id: z.coerce.number(),
npc_spells_effects_id: z.coerce.number(),
npc_spells_id: z.coerce.number(),
prim_melee_type: z.coerce.number(),
private_corpse: z.coerce.number(),
qglobal: z.coerce.number(),
race: z.coerce.number(),
raid_target: z.coerce.number(),
ranged_type: z.coerce.number(),
runspeed: z.coerce.number(),
scalerate: z.coerce.number(),
sec_melee_type: z.coerce.number(),
see_improved_hide: z.coerce.number(),
see_invis: z.coerce.number(),
see_invis_undead: z.coerce.number(),
see_sneak: z.coerce.number(),
size: z.coerce.number(),
slow_mitigation: z.coerce.number(),
spawn_limit: z.coerce.number(),
special_abilities: z.coerce.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
spellscale: z.coerce.number(),
stuck_behavior: z.coerce.number(),
texture: z.coerce.number(),
underwater: z.coerce.number(),
unique_spawn_by_name: z.coerce.number(),
walkspeed: z.coerce.number(),
});
export type NpcTypesType = z.infer<typeof NpcTypesSchema>;
