import {z} from 'zod';
export const SpellsNewSchema= z.object({
AEDuration: z.number(),
Activated: z.number(),
CastingAnim: z.number(),
EndurCost: z.number(),
EndurTimerIndex: z.number(),
EndurUpkeep: z.number(),
EnvironmentType: z.number(),
HateAdded: z.number(),
IsDiscipline: z.number(),
LightType: z.number(),
NoexpendReagent1: z.number(),
NoexpendReagent2: z.number(),
NoexpendReagent3: z.number(),
NoexpendReagent4: z.number(),
RecourseLink: z.number(),
ResistDiff: z.number(),
SpellAffectIndex: z.number(),
TargetAnim: z.number(),
TimeOfDay: z.number(),
TravelType: z.number(),
ai_pt_bonus: z.number(),
allow_spellscribe: z.number(),
allowrest: z.number(),
aoerange: z.number(),
basediff: z.number(),
buffduration: z.number(),
buffdurationformula: z.number(),
can_mgb: z.number(),
cast_not_standing: z.number(),
cast_on_other: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
cast_on_you: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
cast_time: z.number(),
classes1: z.number(),
classes10: z.number(),
classes11: z.number(),
classes12: z.number(),
classes13: z.number(),
classes14: z.number(),
classes15: z.number(),
classes2: z.number(),
classes3: z.number(),
classes4: z.number(),
classes5: z.number(),
classes6: z.number(),
classes7: z.number(),
classes8: z.number(),
classes9: z.number(),
component_counts1: z.number(),
component_counts2: z.number(),
component_counts3: z.number(),
component_counts4: z.number(),
components1: z.number(),
components2: z.number(),
components3: z.number(),
components4: z.number(),
custom_icon: z.number(),
deities0: z.number(),
deities1: z.number(),
deities10: z.number(),
deities11: z.number(),
deities12: z.number(),
deities13: z.number(),
deities14: z.number(),
deities15: z.number(),
deities16: z.number(),
deities2: z.number(),
deities3: z.number(),
deities4: z.number(),
deities5: z.number(),
deities6: z.number(),
deities7: z.number(),
deities8: z.number(),
deities9: z.number(),
deleteable: z.number(),
descnum: z.number(),
disabled: z.number(),
disallow_sit: z.number(),
dot_stacking_exempt: z.number(),
effect_base_value1: z.number(),
effect_base_value10: z.number(),
effect_base_value11: z.number(),
effect_base_value12: z.number(),
effect_base_value2: z.number(),
effect_base_value3: z.number(),
effect_base_value4: z.number(),
effect_base_value5: z.number(),
effect_base_value6: z.number(),
effect_base_value7: z.number(),
effect_base_value8: z.number(),
effect_base_value9: z.number(),
effect_limit_value1: z.number(),
effect_limit_value10: z.number(),
effect_limit_value11: z.number(),
effect_limit_value12: z.number(),
effect_limit_value2: z.number(),
effect_limit_value3: z.number(),
effect_limit_value4: z.number(),
effect_limit_value5: z.number(),
effect_limit_value6: z.number(),
effect_limit_value7: z.number(),
effect_limit_value8: z.number(),
effect_limit_value9: z.number(),
effectdescnum: z.number(),
effectdescnum2: z.number(),
effectid1: z.number(),
effectid10: z.number(),
effectid11: z.number(),
effectid12: z.number(),
effectid2: z.number(),
effectid3: z.number(),
effectid4: z.number(),
effectid5: z.number(),
effectid6: z.number(),
effectid7: z.number(),
effectid8: z.number(),
effectid9: z.number(),
formula1: z.number(),
formula10: z.number(),
formula11: z.number(),
formula12: z.number(),
formula2: z.number(),
formula3: z.number(),
formula4: z.number(),
formula5: z.number(),
formula6: z.number(),
formula7: z.number(),
formula8: z.number(),
formula9: z.number(),
goodEffect: z.number(),
icon: z.number(),
id: z.number(),
mana: z.number(),
max1: z.number(),
max10: z.number(),
max11: z.number(),
max12: z.number(),
max2: z.number(),
max3: z.number(),
max4: z.number(),
max5: z.number(),
max6: z.number(),
max7: z.number(),
max8: z.number(),
max9: z.number(),
memicon: z.number(),
name: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
new_icon: z.number(),
no_partial_resist: z.number(),
nodispell: z.number(),
not_player_spell: z.number(),
npc_category: z.number(),
npc_no_cast: z.number(),
npc_no_los: z.number(),
npc_usefulness: z.number(),
other_casts: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
player_1: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
pushback: z.number(),
pushup: z.number(),
pvp_duration: z.number(),
pvp_duration_cap: z.number(),
pvpresistbase: z.number(),
pvpresistcalc: z.number(),
pvpresistcap: z.number(),
range: z.number(),
recast_time: z.number(),
recovery_time: z.number(),
reflectable: z.number(),
resist_cap: z.number(),
resist_per_level: z.number(),
resisttype: z.number(),
short_buff_box: z.number(),
skill: z.number(),
small_targets_only: z.number(),
spell_category: z.number(),
spell_fades: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
spellanim: z.number(),
spellgroup: z.number(),
suspendable: z.number(),
targettype: z.number(),
teleport_zone: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
typedescnum: z.number(),
uninterruptable: z.number(),
use_persistent_particles: z.number(),
wear_off_message: z.number(),
you_cast: z.string().nullable().transform(e => { 
				if(e === null) return '';
				else return e;
			}),
zonetype: z.number(),
});
export type SpellsNewType = z.infer<typeof SpellsNewSchema>;
